sudo: required
dist: trusty
language: generic
services:
  - docker
cache:
  directories:
  - .cache
branches:
  only:
    - /^20.*$/
    - master

# Travis CI build matrix.  Each entry below will trigger an extra, parallel build on Travis.
matrix:
  include:
  - os: linux
    env:
     - LABEL="arm64_linux"
     - ARCH="arm64"
     - RPM_ARCH="aarch64"
     - TRIPLET="aarch64-linux-gnu"
     - VSCODE_ELECTRON_PLATFORM="arm64"
  - os: linux
    env:
     - LABEL="armhf_linux"
     - ARCH="armhf"
     - RPM_ARCH="armhf"
     - TRIPLET="arm-linux-gnueabihf"
     - VSCODE_ELECTRON_PLATFORM="armv7l"
  # - os: linux
  #   env:
  #   - LABEL="arm64_linux"
  #   - ARCH="arm64"
  #    - RPM_ARCH="aarch64"
    
notifications:
  email: false
  
before_install:
  - gem install package_cloud;
  - sudo apt-get install -y tree;
  - docker pull headmelted/cobbler;

script:
  # - if [[ "${TRAVIS_TAG}" =~ ^20.*$ ]]; then
  - sudo bash -c '. ./dock.sh headmelted/cobbler "export COBBLER_GIT_ENDPOINT=\"https://github.com/Microsoft/vscode.git\"; steps/cook.sh ${ARCH} get patch build package";'
    # else
    #   if [[ "${LABEL}" == "armhf_linux" ]]; then
    #     echo "Merging packages repository back up to Github Pages...";
    #     . ./tools/merge.sh;
    #   fi;
    # fi;
  
  
after_success:
  - tree;
  - package_cloud push headmelted/codebuilds/ubuntu/xenial ./.builds/${LABEL}/.vscode/.build/linux/deb/${ARCH}/deb/*.deb
  - package_cloud push headmelted/codebuilds/fedora/24 ./.builds/${LABEL}/.vscode/.build/linux/rpm/${RPM_ARCH}/*.rpm

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file:
    - ./kitchen/.builds/**/*.deb
    - ./kitchen/.builds/**/*.rpm
    - ./kitchen/.builds/**/*.tar.gz
  skip_cleanup: true
  on:
    repo: headmelted/codebuilds
    tags: true
 
